sonar.projectKey=instana_pipeline-feedback-resource
sonar.organization=instana

# Force SonarCloud to treat files without extensions as Shell scripts
# Since we dont have extensions to our shell scripts it is not getting auto detected
sonar.lang.patterns.shell=assets/*, tests/*

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

sonar.docker.activate=true
sonar.lang.patterns.docker=Dockerfile

sonar.exclusions=tests/**/*.json, examples/**