name: Build and publish image to IBM Cloud Container Registry
on:
  release:
    types: [published]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out release
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout PR code
          fetch-depth: 0 #to pull history
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to IBM Cloud Container Registry
        uses: docker/login-action@v1 
        with:
          registry: icr.io
          username: ${{ secrets.ICR_USERNAME }}
          password: ${{ secrets.ICR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            version=${{ github.event.release.tag_name }}
          push: true
          tags: icr.io/instana/pipeline-feedback-resource
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}